/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef SVR_CONSTANTS_H
#define SVR_CONSTANTS_H

#include "SVR_types.h"

namespace SVR_NS {

class SVRConstants {
 public:
  SVRConstants();

};

extern const SVRConstants g_SVR_constants;

} // namespace

#endif
