// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "SVR.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace  ::SVR_NS;

class SVRHandler : virtual public SVRIf {
 public:
  SVRHandler() {
    // Your initialization goes here
  }

  void add(Data& _return, const Data& v1, const Data& v2) {
    // Your implementation goes here
    printf("add\n");
  }

  void subtract(Data& _return, const Data& v1, const Data& v2) {
    // Your implementation goes here
    printf("subtract\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<SVRHandler> handler(new SVRHandler());
  shared_ptr<TProcessor> processor(new SVRProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

