/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "SVR_constants.h"

namespace SVR_NS {

const SVRConstants g_SVR_constants;

SVRConstants::SVRConstants() {
}

} // namespace

